### PR TITLE
Upgrade slack library

### PR DESCRIPTION
**Pull request by poolski**
Cake-bot talks to Slack using hand-crafted requests, with a smattering of `nlopes/slack` calls to get user info.

Since those days, that package has been taken over by Slack itself under `slack-go/slack` and provides all the functionality that cake-bot needs to interact with Slack.

I've gone through and made a first pass at cleaning up some of homebrew Slack interactions, while keeping the internal APIs consistent. As a result the `slack` internal package has been slimmed down substantially. We could go further but I didn't want to change too much.

Before this can be shipped to Production, we will need to make sure the following OAuth2 scopes are present in the `cake-bot` app in Slack:
- `users:read`, `users:read.email`, `users.profile:read`
- `chat:write` (send messages to channels), `im:write` (send PMs)

> [!WARNING]
> We will need to *reinstall* the app in Slack after making changes to the scopes.

After this is done, I'm going to look at constructing the messages we send to Slack using Slack's message types/blocks, rather than being pure text/JSON payloads.

### CODE REVIEW

**Review by craigmjohnston — APPROVED** [review]
🍰 All looks good to me! 👍

**Comment by geckodeployer** [comment]
(this is kyrill) commenting on a PR review request

**Comment by geckodeployer** [comment]
Another message

**Comment by geckodeployer** [comment]
Feedback

**Review by geckodeployer — CHANGES_REQUESTED** [review]
Change request

**Pull request merged**
